---
# tasks file for rwflowpack
#Copyright 2020 Carnegie Mellon University.
#NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#Released under a MIT (SEI)-style license, please see license.txt or contact permission@sei.cmu.edu for full terms.
#[DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.
#CERT® is registered in the U.S. Patent and Trademark Office by Carnegie Mellon University.
#This Software includes and/or makes use of the following Third-Party Software subject to its own license:
#1. ansible (https://github.com/ansible/ansible/tree/devel/licenses) Copyright 2019 Red Hat, Inc.
#2. molecule (https://github.com/ansible-community/molecule/blob/master/LICENSE) Copyright 2018 Red Hat, Inc.
#3. testinfra (https://github.com/philpep/testinfra/blob/master/LICENSE) Copyright 2020 Philippe Pepiot.
#DM20-0532
- name: Create data root directory
  file:
    path: "{{ data_rootdir }}"
    state: directory
    mode: '0755'

- name: create sensor.conf
  template:
    src: "{{ sensor_conf_template }}"
    dest: "{{ sensor_conf_file_path }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - "restart rwflowpack"

- name: create silk.conf
  template:
    src: "{{ silk_conf_template }}"
    dest: "{{ silk_conf_file_path }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - "restart rwflowpack"

- name: create rwflowpack.conf
  template:
    src: "{{ rwflowpack_conf_template }}"
    dest: "{{ rwflowpack_conf_file_path }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - "restart rwflowpack"

- name: create rwflowpack init script
  template:
    src: "{{ rwflowpack_init_template }}"
    dest: "{{ rwflowpack_init_file_path }}"
    mode: 0755
    owner: root
    group: root
  notify:
    - "reload systemd"
    - "restart rwflowpack"
